### ISSUE TITLE
Bedrock should have instructions to access existing ACR 

### ISSUE THREAD

**Issue by jred55** [microsoft/bedrock#476] opened 2019-07-11 15:01 UTC
**As a:** Developer

**I want:**
Documentation to setup the right privileges for Service Principal access to existing ACR to pull the container image
**So that:**

**Describe the solution you'd like:**
Documentation update
**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment] 2019-07-13 15:59
Possible dupe of #255

**Comment by andrebriggs** [comment] 2020-04-27 07:51
Fixed in #255

**Closed by andrebriggs** 2020-04-27 07:51 UTC
Labels: enhancement
