### ISSUE TITLE
Missing installation documentation

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#702] opened 2019-10-21 17:24 UTC
**Describe the bug:**
Add information on how to install and run `spk`

**Does this require updates to documentation?:**
Yes

- [x] Write documentation on how to install and run spk in the main [readme page](https://github.com/catalystcode/spk)

**Comment by jred55** [comment] 2019-10-25 16:33
This is duplicate of #684

**Closed** 2019-11-01 18:58 UTC
Labels: documentation, effort - XS, enhancement, triage
