### ISSUE TITLE
CLI deployment filter by service doesn't show results for github repos

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#792] opened 2019-11-15 20:19 UTC
**Describe the bug:**
`spk deployment get -s service-name` doesn't show results for github repos

**To Reproduce:**
`spk deployment get -s service-name` where service-name is the name of a service in a github repository.

**Expected behavior:**
It shows the correct search result in the table

Seen:
Empty results table

**Does this require updates to documentation?:**
No

**Comment by andrebriggs** [comment] 2019-12-06 07:17
@edaena @samiya So this only affects GitHub repos? If so let's indicate that in the title

**Comment by samiyaakhtar** [comment] 2020-05-06 01:54
Not able to reproduce for github configurations. Closing

**Closed by samiyaakhtar** 2020-05-06 01:54 UTC
Labels: bug, effort - XS, low - pri
