### ISSUE TITLE
SPK should not assume a service is a directory based in the repo

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1013] opened 2020-02-20 05:35 UTC
**As a:** developer

**I want:** to work with SPK in a manner that does not assume a service is a directory under the repository root.  Most commands - "service create", "create-build-pipeline", etc make the assumption that the service is in a directory under the repo root.  

**Describe the solution you'd like:**. Documentation and command line should be clear about how to avoid this assumption.

**Comment by andrebriggs** [comment] 2020-02-20 19:28
@jmspring the main metadata file that spk service/project commands write to is `bedrock.yaml` which lives at the root. Are you saying the actual source code should be able to live at any directory below the root?

If so I think we can leverage the `bedrock.yaml` to store (or anchor) that information. Perhaps after one calls `spk project init` at the root, they can call `spk service create` with a subdirectory path. This information will be added to the `bedrock.yaml`. Would that work?

**Comment by jmspring** [comment] 2020-02-20 19:56
Yes, leave bedrock.yaml in the root and the remaining files in a spk specific directory.

**Comment by andrebriggs** [comment] 2020-02-24 07:24
@jmspring we have this existing [epic](https://github.com/microsoft/bedrock/issues/943) story that will allow specification of the `path to service`. Would that suffice?

cc @mtarng

**Comment by mtarng** [comment] 2020-02-24 07:50
The work covered in https://github.com/microsoft/bedrock/issues/943 should handle this case.

**Comment by bnookala** [comment] 2020-02-27 09:01
Closing as duplicate of https://github.com/microsoft/bedrock/issues/943

**Closed by bnookala** 2020-02-27 09:01 UTC
Labels: enhancement, triage
